name: Coveralls Upload
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    
    - name: Install dependencies
      run: pip install coveralls coverage PyYAML
      
    - name: Run Coveralls
      run: |
        coverage run -m unittest discover unit_tests/bmi
        coverage run -m unittest discover unit_tests/retirement
        
    - name: Uload to coveralls
      env: 
        COVERALLS_SERVICE_NAME: github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
      
